### ISSUE TITLE
Hard coded path...

### ISSUE THREAD

**Issue by udaygin** [omm9/raspberry#1]
did a git pull and tried to run ./check_internet.sh and got below error 

`thor@asgard:~/src/om/raspberry$ ./check_internet.sh
 
Online

Download = 87.84 Mbps 

Upload =  74.43 Mbps 

Ping =  30.036 ms 

./check_internet.sh: line 46: /home/om/scripts/logs/date_time.txt: No such file or directory

./check_internet.sh: line 47: [: 87.84: integer expression expected`

**Comment by omm9** [comment]
resolved by uday. Now relative path is being used.
